import './globals.css';
import Head from 'next/head';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto"
          />
      </Head>
      <div>
        {children}
      </div>
    </>
  );
};

export default RootLayout;
